In [1]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from intake import open_catalog
import cartopy.io.shapereader as shpreader
import mygrads as mg
import Ngl
import Nio
import fiona
import sys
np.set_printoptions(threshold=sys.maxsize)

In [2]:
f='/project/xprecip/merra2_ncfiles/precip/*.nc'
DS1=xr.open_mfdataset(f,combine='nested',concat_dim='time')
DS1

<xarray.Dataset>
Dimensions:      (lat: 55, lon: 107, time: 371064)
Coordinates:
  * time         (time) datetime64[ns] 1980-01-01T00:30:00 ... 2021-09-30T23:...
  * lon          (lon) float64 -126.9 -126.2 -125.6 ... -61.88 -61.25 -60.62
  * lat          (lat) float64 23.0 23.5 24.0 24.5 25.0 ... 48.5 49.0 49.5 50.0
Data variables:
    PRECTOTCORR  (time, lat, lon) float32 dask.array<chunksize=(24, 55, 107), meta=np.ndarray>
Attributes: (12/32)
    CDI:                               Climate Data Interface version 1.9.8 (...
    Conventions:                       CF-1
    History:                           Original file generated: Sat May 31 17...
    Comment:                           GMAO filename: d5124_m2_jan79.tavg1_2d...
    Filename:                          MERRA2_100.tavg1_2d_flx_Nx.19800101.nc4
    Institution:                       NASA Global Modeling and Assimilation ...
    ...                                ...
    RangeBeginningDate:                1980-01-01
    RangeBeginningTime:                00:00:00.000000
    RangeEndingDate:                   1980-01-01
    RangeEndingTime:                   23:59:59.000000
    history_L34RS:                     'Created by L34RS v1.4.2 @ NASA GES DI...
    CDO:                               Climate Data Operators version 1.9.8 (...

In [3]:
sorted=DS1.sortby("time")
sorted

<xarray.Dataset>
Dimensions:      (lat: 55, lon: 107, time: 371064)
Coordinates:
  * time         (time) datetime64[ns] 1980-01-01T00:30:00 ... 2022-04-30T23:...
  * lon          (lon) float64 -126.9 -126.2 -125.6 ... -61.88 -61.25 -60.62
  * lat          (lat) float64 23.0 23.5 24.0 24.5 25.0 ... 48.5 49.0 49.5 50.0
Data variables:
    PRECTOTCORR  (time, lat, lon) float32 dask.array<chunksize=(24, 55, 107), meta=np.ndarray>
Attributes: (12/32)
    CDI:                               Climate Data Interface version 1.9.8 (...
    Conventions:                       CF-1
    History:                           Original file generated: Sat May 31 17...
    Comment:                           GMAO filename: d5124_m2_jan79.tavg1_2d...
    Filename:                          MERRA2_100.tavg1_2d_flx_Nx.19800101.nc4
    Institution:                       NASA Global Modeling and Assimilation ...
    ...                                ...
    RangeBeginningDate:                1980-01-01
    RangeBeginningTime:                00:00:00.000000
    RangeEndingDate:                   1980-01-01
    RangeEndingTime:                   23:59:59.000000
    history_L34RS:                     'Created by L34RS v1.4.2 @ NASA GES DI...
    CDO:                               Climate Data Operators version 1.9.8 (...

In [4]:
one_year=sorted['PRECTOTCORR'].loc['1980-01-01':'1980-01-31']

In [5]:
washington_precip=one_year.sel(lat=39,lon=-77,method='nearest')
washington_precip

<xarray.DataArray 'PRECTOTCORR' (time: 744)>
dask.array<getitem, shape=(744,), dtype=float32, chunksize=(24,), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 1980-01-01T00:30:00 ... 1980-01-31T23:30:00
    lon      float64 -76.88
    lat      float64 39.0
Attributes:
    standard_name:   total_precipitation
    long_name:       total_precipitation
    units:           kg m-2 s-1
    fmissing_value:  1000000000000000.0
    vmax:            1000000000000000.0
    vmin:            -1000000000000000.0

In [6]:
jan_1980=washington_precip.values

In [7]:
jan_1980

array([8.78230821e-12, 8.33466629e-12, 7.97584221e-12, 5.26512167e-12,
       3.28626015e-12, 7.93676236e-12, 1.68185466e-11, 2.13375984e-11,
       2.63682409e-11, 4.34425829e-11, 5.72271119e-11, 7.72217845e-11,
       2.49656296e-09, 3.47972673e-09, 6.68660505e-09, 9.82618076e-09,
       1.61744538e-08, 3.33093340e-08, 6.51925802e-08, 7.27886800e-08,
       9.07166395e-08, 8.55070539e-08, 5.88624971e-08, 3.00497049e-08,
       5.35328581e-09, 7.04312697e-09, 3.69618647e-08, 6.61239028e-08,
       6.62112143e-08, 7.00238161e-08, 4.91563696e-08, 2.61061359e-08,
       1.13541319e-08, 1.39225449e-08, 1.45082595e-08, 1.21508492e-08,
       3.30970806e-11, 1.40296663e-11, 1.66906489e-11, 2.92601499e-11,
       3.50439677e-11, 3.29265504e-11, 2.66524580e-11, 2.24389396e-11,
       2.36397568e-11, 2.02646788e-11, 1.50350843e-11, 9.17665943e-12,
       6.00408612e-12, 7.21200877e-12, 3.85540488e-11, 1.98667749e-10,
       5.56383384e-10, 9.89984983e-10, 1.55614543e-09, 1.83126758e-09,
      

In [8]:
test_array=washington_precip/washington_precip
test_array

<xarray.DataArray 'PRECTOTCORR' (time: 744)>
dask.array<truediv, shape=(744,), dtype=float32, chunksize=(24,), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 1980-01-01T00:30:00 ... 1980-01-31T23:30:00
    lon      float64 -76.88
    lat      float64 39.0

In [9]:
test_array_values=test_array.values

/homes/areed29/.conda/envs/clim680/lib/python3.6/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


In [10]:
test_array_values

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1., nan, nan, nan, nan, nan, nan, nan,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [12]:
resample_test=test_array.resample(time='6H').sum()
resample_test

<xarray.DataArray 'PRECTOTCORR' (time: 124)>
dask.array<stack, shape=(124,), dtype=float32, chunksize=(1,), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 1980-01-01 ... 1980-01-31T18:00:00
    lon      float64 -76.88
    lat      float64 39.0

In [14]:
print(resample_test.values)

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 5. 0. 6.
 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6. 0. 0. 0. 0. 3. 0. 2. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0. 2. 6. 6. 6. 6. 6. 6. 6. 6. 6.
 6. 6. 6. 6.]


/homes/areed29/.conda/envs/clim680/lib/python3.6/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


In [18]:
resample_test_2=test_array.resample(time='6H').reduce(np.sum)
resample_test_2

<xarray.DataArray 'PRECTOTCORR' (time: 124)>
dask.array<stack, shape=(124,), dtype=float32, chunksize=(1,), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 1980-01-01 ... 1980-01-31T18:00:00
    lon      float64 -76.88
    lat      float64 39.0

In [19]:
print(resample_test_2.values)

[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.
  6.  6.  6. nan nan  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6. nan nan nan nan  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  6. nan nan nan nan nan nan nan  6.  6.  6.  6.  6.
  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6. nan nan
 nan nan nan  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]


/homes/areed29/.conda/envs/clim680/lib/python3.6/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


In [20]:
resample_test_3=test_array.resample(time='6H').reduce(np.nansum)
resample_test_3.values

/homes/areed29/.conda/envs/clim680/lib/python3.6/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in true_divide
  return func(*(_execute_task(a, cache) for a in args))


array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 5., 0., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 0., 0., 0., 0., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 0., 0., 0., 0., 3., 0., 2.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 0., 0., 0., 0., 2., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6.], dtype=float32)